### ISSUE TITLE
Produces a dist folder with local references

### ISSUE THREAD

**Issue by jorisw** [chromaui/learnstorybook-design-system#9]
I've started with a clean copy of the this repo, hit `yarn build`, and `dist/` is now full of references to my local hard drive:

![image](https://user-images.githubusercontent.com/30017/80792541-f3cde880-8b94-11ea-81ed-7e24d2600575.png)

**Comment by jonniebigodes** [comment]
Closing this issue as it's no longer applicable with the latest version. The issue is missing information related to babel. Which is already documented.
